pred_region: 'amhara'

start_date: '2017-01-01'
end_date: '2019-12-31'

max_cloud_frac: 0.3

month_valid_start_day: 4
month_valid_end_day: 26

model_filename: 'trained_all_regions' # trained_amhara
norm_filename: 'all_regions_norm_array'

# Conditions for valid prediction
srtm_max_slope: 800
min_evi_ratio_90_10: 2

